// Hand-written fallback for the wasm-bindgen output normally generated by
// `npm run build:wasm` (requires Rust + wasm-pack). It is copied into
// WASM_FileProcessor/pkg/ by WASM_FileProcessor/ensure-pkg.mjs whenever that
// toolchain isn't available, so `npm run check` and `npm run build` succeed on
// any machine. It satisfies the same export shape as the real module, but
// every operation rejects with a clear error - callers already fall back to
// the pure TypeScript parser (see Processor.enableWasmProcessing / loadFile).

const NOT_BUILT_MESSAGE =
   'WASM G-code processor is not built. Run `npm run build:wasm` on a machine with Rust + wasm-pack installed, then rebuild.'

export default async function init() {
   throw new Error(NOT_BUILT_MESSAGE)
}

export function get_version() {
   return 'unbuilt'
}

export class ProcessingResult {
   constructor() {
      throw new Error(NOT_BUILT_MESSAGE)
   }
}

export class PositionData {
   constructor() {
      throw new Error(NOT_BUILT_MESSAGE)
   }
}

export class RenderBuffers {
   constructor() {
      throw new Error(NOT_BUILT_MESSAGE)
   }
}

export class GCodeProcessor {
   constructor() {
      throw new Error(NOT_BUILT_MESSAGE)
   }
}
