use crate::gcode_line::Color4;
use crate::slicers::{FeatureState, LayerInfo, SlicerBase};

/// (key, color, is_perimeter, is_support) - transcribed verbatim from
/// src/GCodeParsers/kirimoto.ts. Exact-string lookup, no normalization heuristics.
const FEATURES: &[(&str, [f64; 4], bool, bool)] = &[
    ("SHELLS", [1.0, 0.9, 0.3, 1.0], true, false),
    ("SPARSE INFILL", [0.59, 0.19, 0.16, 1.0], false, false),
    ("SOLID FILL", [0.59, 0.19, 0.8, 1.0], true, false),
    ("UNKNOWN", [0.5, 0.5, 0.5, 1.0], false, false),
    ("SUPPORT MATERIAL", [0.5, 0.5, 0.5, 1.0], false, true),
    ("SUPPORT MATERIAL INTERFACE", [0.5, 0.5, 0.5, 1.0], false, true),
    ("OVERHANG PERIMETER", [0.5, 0.5, 0.5, 1.0], true, false),
    ("WIPE TOWER", [0.5, 0.5, 0.5, 1.0], true, false),
];

pub struct KiriMotoSlicer {
    name: String,
    state: FeatureState,
}

impl KiriMotoSlicer {
    pub fn new() -> Self {
        Self {
            name: "KiriMoto".to_string(),
            state: FeatureState::default(),
        }
    }
}

impl SlicerBase for KiriMotoSlicer {
    fn process_comment(&mut self, comment: &str) {
        let Some(feature_raw) = comment.strip_prefix(";TYPE:") else {
            return;
        };
        let key = feature_raw.trim();
        if let Some(&(_, color, is_perimeter, is_support)) = FEATURES.iter().find(|(k, ..)| *k == key) {
            self.state.color = Color4::new(color[0], color[1], color[2], color[3]);
            self.state.is_perimeter = is_perimeter;
            self.state.is_support = is_support;
        } else {
            self.state.color = Color4::white();
            self.state.is_perimeter = true;
            self.state.is_support = false;
        }
    }

    fn is_perimeter(&self) -> bool {
        self.state.is_perimeter
    }

    fn is_support(&self) -> bool {
        self.state.is_support
    }

    fn get_feature_color(&self) -> Color4 {
        self.state.color.clone()
    }

    fn parse_layer_info(&self, _comment: &str) -> Option<LayerInfo> {
        None
    }

    fn get_temperature_from_comment(&self, _comment: &str) -> Option<f64> {
        None
    }

    fn detect_slicer(file_content: &str) -> bool
    where
        Self: Sized,
    {
        file_content.contains("; Generated by Kiri:Moto")
    }

    fn get_name(&self) -> &str {
        &self.name
    }

    fn get_version_info(&self, _file_content: &str) -> Option<String> {
        None
    }
}

impl Default for KiriMotoSlicer {
    fn default() -> Self {
        Self::new()
    }
}
