use crate::gcode_line::Color4;
use crate::slicers::{FeatureState, LayerInfo, SlicerBase};

/// (key, color, is_perimeter, is_support) - transcribed verbatim from
/// src/GCodeParsers/orcaslicer.ts. OrcaSlicer's feature vocabulary is entirely its own (not a
/// Prusa variant) - exact-string lookup, no normalization heuristics.
const FEATURES: &[(&str, [f64; 4], bool, bool)] = &[
    ("OUTER WALL", [1.0, 0.9, 0.3, 1.0], true, false),
    ("INNER WALL", [1.0, 0.49, 0.22, 1.0], false, false),
    ("OVERHANG WALL", [0.15, 0.16, 0.75, 1.0], false, false),
    ("SPARSE INFILL", [0.69, 0.19, 0.16, 1.0], false, false),
    ("INTERNAL SOLID INFILL", [0.59, 0.33, 0.8, 1.0], false, false),
    ("TOP SURFACE", [0.7, 0.22, 0.22, 1.0], true, false),
    ("BOTTOM SURFACE", [0.4, 0.36, 0.78, 1.0], true, false),
    ("BRIDGE", [0.3, 0.5, 0.73, 1.0], false, false),
    ("CUSTOM", [0.37, 0.82, 0.58, 1.0], false, false),
    ("SUPPORT", [0.0, 1.0, 0.0, 1.0], false, true),
    ("SUPPORT INTERFACE", [0.12, 0.38, 0.13, 1.0], false, true),
    ("PRIME TOWER", [0.7, 0.89, 0.67, 1.0], false, false),
];

pub struct OrcaSlicer {
    name: String,
    state: FeatureState,
}

impl OrcaSlicer {
    pub fn new() -> Self {
        Self {
            name: "OrcaSlicer".to_string(),
            state: FeatureState::default(),
        }
    }
}

impl SlicerBase for OrcaSlicer {
    fn process_comment(&mut self, comment: &str) {
        let Some(feature_raw) = comment.strip_prefix(";TYPE:") else {
            return;
        };
        let key = feature_raw.trim();
        if let Some(&(_, color, is_perimeter, is_support)) = FEATURES.iter().find(|(k, ..)| *k == key) {
            self.state.color = Color4::new(color[0], color[1], color[2], color[3]);
            self.state.is_perimeter = is_perimeter;
            self.state.is_support = is_support;
        } else {
            self.state.color = Color4::white();
            self.state.is_perimeter = true;
            self.state.is_support = false;
        }
    }

    fn is_perimeter(&self) -> bool {
        self.state.is_perimeter
    }

    fn is_support(&self) -> bool {
        self.state.is_support
    }

    fn get_feature_color(&self) -> Color4 {
        self.state.color.clone()
    }

    fn parse_layer_info(&self, comment: &str) -> Option<LayerInfo> {
        if comment.contains("LAYER_CHANGE") || comment.starts_with("; Z:") {
            if let Some(z_start) = comment.find("; Z:") {
                let z_line = &comment[z_start + 4..];
                let z_end = z_line.find('\n').unwrap_or(z_line.len());
                let z_str = z_line[..z_end].trim();
                if let Ok(z_pos) = z_str.parse::<f64>() {
                    let layer_num = if let Some(layer_start) = comment.find("LAYER:") {
                        let layer_line = &comment[layer_start + 6..];
                        if let Some(layer_end) = layer_line.find(&['\n', ' ', ';'][..]) {
                            layer_line[..layer_end].trim().parse::<u32>().unwrap_or(0)
                        } else {
                            0
                        }
                    } else {
                        0
                    };

                    return Some(LayerInfo {
                        layer_number: layer_num,
                        layer_height: 0.2,
                        z_position: z_pos,
                    });
                }
            }
        }
        None
    }

    fn get_temperature_from_comment(&self, comment: &str) -> Option<f64> {
        if comment.contains("temperature") || comment.contains("nozzle_temperature") {
            for word in comment.split_whitespace() {
                if let Ok(temp) = word.trim_matches(&[';', '°', 'C', '=', ':'][..]).parse::<f64>() {
                    if temp > 0.0 && temp < 500.0 {
                        return Some(temp);
                    }
                }
            }
        }
        None
    }

    fn detect_slicer(file_content: &str) -> bool
    where
        Self: Sized,
    {
        // Matches TS's slicerFactory.ts pattern exactly ('generated by OrcaSlicer ', with the
        // trailing space) - the previous extra "; OrcaSlicer" clause has no TS equivalent
        file_content.contains("generated by OrcaSlicer ")
    }

    fn get_name(&self) -> &str {
        &self.name
    }

    fn get_version_info(&self, file_content: &str) -> Option<String> {
        if let Some(start) = file_content.find("generated by OrcaSlicer ") {
            let version_line = &file_content[start + 24..];
            let end = version_line.find(' ').or_else(|| version_line.find('\n')).unwrap_or(version_line.len());
            return Some(version_line[..end].trim().to_string());
        }
        None
    }
}

impl Default for OrcaSlicer {
    fn default() -> Self {
        Self::new()
    }
}
