use crate::gcode_line::Color4;
use crate::slicers::{detect_slicer, SlicerBase};

#[cfg(test)]
mod tests {
    use super::*;

    // Test data - sample G-code headers from different slicers
    const PRUSA_GCODE: &str = r#";
; generated by PrusaSlicer 2.6.0+win64 on 2023-09-01 at 12:30:45 UTC
; external perimeters extrusion width = 0.45mm
; perimeters extrusion width = 0.45mm

G28 ; home all axes
;TYPE:PERIMETER
G1 X10 Y10 E5 F1800
;TYPE:EXTERNAL PERIMETER
G1 X20 Y20 E10 F1800
;TYPE:INTERNAL INFILL
G1 X30 Y30 E15 F1800"#;

    const CURA_GCODE: &str = r#";FLAVOR:Marlin
;TIME:3600
;Filament used: 5.12345m
;Layer height: 0.2
;Generated with Cura_SteamEngine 5.4.0

G28 ;Home
;TYPE:SKIRT
G1 X5 Y5 E2 F1500
;TYPE:WALL-OUTER
G1 X15 Y15 E7 F1500
;TYPE:FILL
G1 X25 Y25 E12 F1500"#;

    const ORCA_GCODE: &str = r#";
; generated by OrcaSlicer 1.7.0 on 2023-09-01 at 12:30:45 UTC
; layer_height = 0.2
; first_layer_height = 0.2

G28 ; home all axes
;TYPE:INNER WALL
G1 X10 Y10 E5 F1800
;TYPE:OUTER WALL
G1 X20 Y20 E10 F1800"#;

    const SUPERSLICER_GCODE: &str = r#";
; generated by SuperSlicer 2.5.59 on 2023-09-01 at 12:30:45 UTC
; external perimeters extrusion width = 0.45mm

G28 ; home all axes
;TYPE:PERIMETER
G1 X10 Y10 E5 F1800
;TYPE:EXTERNAL PERIMETER
G1 X20 Y20 E10 F1800"#;

    const IDEAMAKER_GCODE: &str = r#";Sliced by ideaMaker
;TYPE:EXTERNAL PERIMETER
G1 X10 Y10 E5 F1800"#;

    const KIRIMOTO_GCODE: &str = r#"; Generated by Kiri:Moto
;TYPE:SHELLS
G1 X10 Y10 E5 F1800"#;

    const GENERIC_GCODE: &str = r#"G28 ; home all axes
G1 X10 Y10 E5 F1800
G1 X20 Y20 E10 F1800"#;

    fn colors_equal(a: &Color4, b: &Color4, tolerance: f64) -> bool {
        (a.r - b.r).abs() < tolerance
            && (a.g - b.g).abs() < tolerance
            && (a.b - b.b).abs() < tolerance
            && (a.a - b.a).abs() < tolerance
    }

    fn assert_feature(slicer: &mut dyn SlicerBase, comment: &str, color: [f64; 4], perimeter: bool, support: bool) {
        slicer.process_comment(comment);
        let expected = Color4::new(color[0], color[1], color[2], color[3]);
        assert!(
            colors_equal(&slicer.get_feature_color(), &expected, 0.001),
            "{comment}: expected color {:?}, got {:?}",
            expected,
            slicer.get_feature_color()
        );
        assert_eq!(slicer.is_perimeter(), perimeter, "{comment}: perimeter flag mismatch");
        assert_eq!(slicer.is_support(), support, "{comment}: support flag mismatch");
    }

    // ---- Detection ----

    #[test]
    fn test_slicer_detection_prusa() {
        assert_eq!(detect_slicer(PRUSA_GCODE).get_name(), "PrusaSlicer");
    }

    #[test]
    fn test_slicer_detection_cura() {
        assert_eq!(detect_slicer(CURA_GCODE).get_name(), "Cura");
    }

    #[test]
    fn test_slicer_detection_superslicer() {
        assert_eq!(detect_slicer(SUPERSLICER_GCODE).get_name(), "SuperSlicer");
    }

    #[test]
    fn test_slicer_detection_orca() {
        assert_eq!(detect_slicer(ORCA_GCODE).get_name(), "OrcaSlicer");
    }

    #[test]
    fn test_slicer_detection_ideamaker() {
        assert_eq!(detect_slicer(IDEAMAKER_GCODE).get_name(), "ideaMaker");
    }

    #[test]
    fn test_slicer_detection_kirimoto() {
        assert_eq!(detect_slicer(KIRIMOTO_GCODE).get_name(), "KiriMoto");
    }

    #[test]
    fn test_slicer_detection_generic() {
        assert_eq!(detect_slicer(GENERIC_GCODE).get_name(), "Generic");
    }

    #[test]
    fn test_cura_detection_does_not_match_bare_flavor_header() {
        // A previous version matched any ";FLAVOR:" header, misrouting plain Marlin-flavor files
        // from other slicers into Cura's feature-comment parsing. TS's slicerFactory.ts only
        // matches ';Generated with Cura_SteamEngine'.
        let marlin_only = ";FLAVOR:Marlin\nG28\nG1 X10 Y10 E5 F1800";
        assert_ne!(detect_slicer(marlin_only).get_name(), "Cura");
        assert_eq!(detect_slicer(marlin_only).get_name(), "Generic");
    }

    // ---- Default state before any comment (matches TS SlicerBase defaults exactly) ----

    #[test]
    fn test_default_state_before_any_comment() {
        for gcode in [PRUSA_GCODE, CURA_GCODE, ORCA_GCODE, SUPERSLICER_GCODE, GENERIC_GCODE] {
            let slicer = detect_slicer(gcode);
            assert!(colors_equal(&slicer.get_feature_color(), &Color4::white(), 0.001));
            assert!(slicer.is_perimeter());
            assert!(!slicer.is_support());
        }
    }

    // ---- PrusaSlicer: table-driven, matches src/GCodeParsers/prusaslicer.ts exactly ----

    #[test]
    fn test_prusa_feature_table() {
        let mut slicer = detect_slicer(PRUSA_GCODE);
        assert_feature(slicer.as_mut(), ";TYPE:PERIMETER", [1.0, 0.9, 0.3, 1.0], true, false);
        assert_feature(slicer.as_mut(), ";TYPE:EXTERNAL PERIMETER", [1.0, 0.5, 0.2, 1.0], true, false);
        assert_feature(slicer.as_mut(), ";TYPE:INTERNAL INFILL", [0.59, 0.19, 0.16, 1.0], false, false);
        assert_feature(slicer.as_mut(), ";TYPE:SOLID INFILL", [0.59, 0.19, 0.8, 1.0], false, false);
        assert_feature(slicer.as_mut(), ";TYPE:TOP SOLID INFILL", [0.95, 0.25, 0.25, 1.0], false, false);
        assert_feature(slicer.as_mut(), ";TYPE:BRIDGE INFILL", [0.3, 0.5, 0.73, 1.0], false, false);
        assert_feature(slicer.as_mut(), ";TYPE:GAP FILL", [1.0, 1.0, 1.0, 1.0], false, false);
        assert_feature(slicer.as_mut(), ";TYPE:SKIRT", [0.0, 0.53, 0.43, 1.0], false, false);
        assert_feature(slicer.as_mut(), ";TYPE:SUPPORTED MATERIAL", [0.0, 1.0, 0.0, 1.0], false, true);
        assert_feature(slicer.as_mut(), ";TYPE:SUPPORTED MATERIAL INTERFACE", [0.0, 0.5, 0.0, 1.0], false, true);
        assert_feature(slicer.as_mut(), ";TYPE:SUPPORT MATERIAL", [0.5, 0.5, 0.5, 1.0], false, true);
        assert_feature(slicer.as_mut(), ";TYPE:OVERHANG PERIMETER", [0.5, 0.5, 0.5, 1.0], true, false);
        assert_feature(slicer.as_mut(), ";TYPE:WIPE TOWER", [0.5, 0.5, 0.5, 1.0], false, false);
        assert_feature(slicer.as_mut(), ";TYPE:CUSTOM", [0.5, 0.5, 0.5, 1.0], false, false);
        assert_feature(slicer.as_mut(), ";TYPE:UNKNOWN", [0.5, 0.5, 0.5, 1.0], false, false);
    }

    #[test]
    fn test_prusa_synonym_heuristics() {
        // Lowercase/hyphenated/spaced variants that don't hit the table directly, resolved by
        // prusaslicer.ts's normalization+synonym heuristics
        let mut slicer = detect_slicer(PRUSA_GCODE);
        assert_feature(slicer.as_mut(), ";TYPE:top-solid_infill", [0.95, 0.25, 0.25, 1.0], false, false);
        assert_feature(slicer.as_mut(), ";TYPE:external-perimeter", [1.0, 0.5, 0.2, 1.0], true, false);
        assert_feature(slicer.as_mut(), ";TYPE:internal infill", [0.59, 0.19, 0.16, 1.0], false, false);
        assert_feature(slicer.as_mut(), ";TYPE:support-interface", [0.5, 0.5, 0.5, 1.0], false, true);
        assert_feature(slicer.as_mut(), ";TYPE:support", [0.5, 0.5, 0.5, 1.0], false, true);
    }

    #[test]
    fn test_prusa_unknown_feature_falls_back_to_white_perimeter() {
        let mut slicer = detect_slicer(PRUSA_GCODE);
        assert_feature(slicer.as_mut(), ";TYPE:UNKNOWN_FEATURE_TYPE", [1.0, 1.0, 1.0, 1.0], true, false);
    }

    #[test]
    fn test_prusa_version_extraction() {
        let slicer = detect_slicer(PRUSA_GCODE);
        assert_eq!(slicer.get_version_info(PRUSA_GCODE), Some("2.6.0+win64".to_string()));
    }

    #[test]
    fn test_prusa_layer_info_parsing() {
        let content = "; LAYER_CHANGE\n; Z:0.3\n; layer num/total_layer_count: 2/245";
        let slicer = detect_slicer(PRUSA_GCODE);
        let layer_info = slicer.parse_layer_info(content).expect("layer info");
        assert_eq!(layer_info.layer_number, 2);
        assert_eq!(layer_info.z_position, 0.3);
    }

    // ---- Cura: table-driven, exact-match (no case folding) ----

    #[test]
    fn test_cura_feature_table() {
        let mut slicer = detect_slicer(CURA_GCODE);
        assert_feature(slicer.as_mut(), ";TYPE:SKIN", [1.0, 0.9, 0.3, 1.0], true, false);
        assert_feature(slicer.as_mut(), ";TYPE:WALL-OUTER", [1.0, 0.5, 0.2, 1.0], true, false);
        assert_feature(slicer.as_mut(), ";TYPE:WALL-INNER", [0.59, 0.19, 0.16, 1.0], false, false);
        assert_feature(slicer.as_mut(), ";TYPE:FILL", [0.95, 0.25, 0.25, 1.0], false, false);
        assert_feature(slicer.as_mut(), ";TYPE:SKIRT", [0.0, 0.53, 0.43, 1.0], false, false);
        assert_feature(slicer.as_mut(), ";TYPE:SUPPORT", [0.0, 0.53, 0.43, 1.0], false, true);
    }

    #[test]
    fn test_cura_version_extraction() {
        let slicer = detect_slicer(CURA_GCODE);
        assert_eq!(slicer.get_version_info(CURA_GCODE), Some("5.4.0".to_string()));
    }

    // ---- SuperSlicer: same palette as Prusa, but deliberately different flags ----

    #[test]
    fn test_superslicer_flags_differ_from_prusa() {
        let mut super_slicer = detect_slicer(SUPERSLICER_GCODE);
        let mut prusa_slicer = detect_slicer(PRUSA_GCODE);

        super_slicer.process_comment(";TYPE:PERIMETER");
        prusa_slicer.process_comment(";TYPE:PERIMETER");
        assert!(!super_slicer.is_perimeter(), "SuperSlicer PERIMETER should be perimeter:false");
        assert!(prusa_slicer.is_perimeter(), "PrusaSlicer PERIMETER should be perimeter:true");

        super_slicer.process_comment(";TYPE:TOP SOLID INFILL");
        prusa_slicer.process_comment(";TYPE:TOP SOLID INFILL");
        assert!(super_slicer.is_perimeter(), "SuperSlicer TOP SOLID INFILL should be perimeter:true");
        assert!(!prusa_slicer.is_perimeter(), "PrusaSlicer TOP SOLID INFILL should be perimeter:false");

        super_slicer.process_comment(";TYPE:SUPPORT MATERIAL");
        prusa_slicer.process_comment(";TYPE:SUPPORT MATERIAL");
        assert!(!super_slicer.is_support(), "SuperSlicer SUPPORT MATERIAL should be support:false");
        assert!(prusa_slicer.is_support(), "PrusaSlicer SUPPORT MATERIAL should be support:true");
    }

    // ---- OrcaSlicer: entirely its own vocabulary ----

    #[test]
    fn test_orca_feature_table() {
        let mut slicer = detect_slicer(ORCA_GCODE);
        assert_feature(slicer.as_mut(), ";TYPE:OUTER WALL", [1.0, 0.9, 0.3, 1.0], true, false);
        assert_feature(slicer.as_mut(), ";TYPE:INNER WALL", [1.0, 0.49, 0.22, 1.0], false, false);
        assert_feature(slicer.as_mut(), ";TYPE:TOP SURFACE", [0.7, 0.22, 0.22, 1.0], true, false);
        assert_feature(slicer.as_mut(), ";TYPE:BOTTOM SURFACE", [0.4, 0.36, 0.78, 1.0], true, false);
        assert_feature(slicer.as_mut(), ";TYPE:SUPPORT", [0.0, 1.0, 0.0, 1.0], false, true);
        assert_feature(slicer.as_mut(), ";TYPE:SUPPORT INTERFACE", [0.12, 0.38, 0.13, 1.0], false, true);
        assert_feature(slicer.as_mut(), ";TYPE:PRIME TOWER", [0.7, 0.89, 0.67, 1.0], false, false);
    }

    // ---- ideaMaker / KiriMoto: spot checks ----

    #[test]
    fn test_ideamaker_feature_table() {
        let mut slicer = detect_slicer(IDEAMAKER_GCODE);
        assert_feature(slicer.as_mut(), ";TYPE:EXTERNAL PERIMETER", [1.0, 0.5, 0.2, 1.0], true, false);
        assert_feature(slicer.as_mut(), ";TYPE:WIPE TOWER", [0.5, 0.5, 0.5, 1.0], true, false);
    }

    #[test]
    fn test_kirimoto_feature_table() {
        let mut slicer = detect_slicer(KIRIMOTO_GCODE);
        assert_feature(slicer.as_mut(), ";TYPE:SHELLS", [1.0, 0.9, 0.3, 1.0], true, false);
        assert_feature(slicer.as_mut(), ";TYPE:SPARSE INFILL", [0.59, 0.19, 0.16, 1.0], false, false);
    }

    // ---- Generic: no feature parsing at all ----

    #[test]
    fn test_generic_slicer_behavior() {
        let mut slicer = detect_slicer(GENERIC_GCODE);
        assert_eq!(slicer.get_name(), "Generic");
        slicer.process_comment(";TYPE:PERIMETER");
        // Generic never updates state - stays at the SlicerBase defaults
        assert!(colors_equal(&slicer.get_feature_color(), &Color4::white(), 0.001));
        assert!(slicer.is_perimeter());
        assert!(!slicer.is_support());
    }

    #[test]
    fn test_slicer_detection_consistency() {
        let slicer1 = detect_slicer(PRUSA_GCODE);
        let slicer2 = detect_slicer(PRUSA_GCODE);
        assert_eq!(slicer1.get_name(), slicer2.get_name());
    }
}
